# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='action',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='market',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=10),
        ),
    ]
