# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0003_auto_20170904_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='created_on',
            field=models.DateField(auto_now_add=True, default='2017-09-05'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allocation',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
