# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0004_auto_20170904_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_counterparty', models.BooleanField(default=False)),
                ('is_agent', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='counterparty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tradepath.Organization'),
        ),
    ]
