# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0005_auto_20170904_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('DEFAULT', 'Default'), ('COINVEST', 'Co-Invest')], default='DEFAULT', max_length=10)),
                ('sort_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradepath.Allocation')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradepath.Condition')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradepath.Portfolio')),
            ],
        ),
        migrations.AlterField(
            model_name='trade',
            name='action',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='market',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], default='PRIMARY', max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=10),
        ),
        migrations.AddField(
            model_name='path',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradepath.Requirement'),
        ),
        migrations.AddField(
            model_name='action',
            name='path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradepath.Path'),
        ),
    ]
