# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0006_auto_20170904_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='condition',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('COINVEST', 'Co-Invest'), ('BUY', 'Buy')], default='DEFAULT', max_length=10),
        ),
    ]
