# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0007_auto_20170904_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='path',
        ),
        migrations.AddField(
            model_name='path',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50),
        ),
        migrations.DeleteModel(
            name='Action',
        ),
    ]
