# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0009_auto_20170913_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='settle_date',
            field=models.DateField(null=True),
        ),
    ]
