# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0010_allocation_settle_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='external_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='external_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='external_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='issuer',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='issuer',
            name='external_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='issuer',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='external_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='path',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='path',
            name='external_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='path',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='external_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='external_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='external_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('SETTLED', 'Settled'), ('HOLD', 'On Hold'), ('UPSTREAM', 'Upstream')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
