# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0011_auto_20170917_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='completed_on',
            field=models.DateField(null=True),
        ),
    ]
