# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0012_path_completed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='venue_allocation_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='venue',
            field=models.CharField(choices=[('CLEARPAR', 'ClearPar'), ('OFFLINE', 'Offline')], default='CLEARPAR', max_length=15),
        ),
        migrations.AddField(
            model_name='trade',
            name='venue_trade_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
