# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0015_auto_20180301_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='venue',
            field=models.CharField(choices=[('CLEARPAR', 'ClearPar'), ('DIRECT', 'Direct Settlement'), ('OFFLINE', 'Offline'), ('OTHER', 'OTHER')], default='CLEARPAR', max_length=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='venue_trade_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
