# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0017_auto_20180301_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='condition_type',
            field=models.CharField(choices=[('TASK', 'Task'), ('ACTIVITY', 'Activity'), ('APPROVAL', 'Approval'), ('CONFIRMATION', 'Confirmation')], default='TASK', max_length=50),
        ),
        migrations.AlterField(
            model_name='condition',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
