# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0018_auto_20180301_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='condition_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
