# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0019_condition_condition_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='parent_portfolio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
