# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-02 00:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0020_auto_20180301_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='rules',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None), blank=True, null=True, size=8),
        ),
    ]
