# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-02 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0021_portfolio_rules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='amount',
            new_name='quantity',
        ),
    ]
