# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-02 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0023_auto_20180301_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='condition_type',
            field=models.CharField(choices=[('TASK', 'Task'), ('ACTIVITY', 'Activity'), ('APPROVAL', 'Approval'), ('CONFIRMATION', 'Confirmation')], default='Task', max_length=50),
        ),
        migrations.AlterField(
            model_name='condition',
            name='entity',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('portfolio', 'Portfolio'), ('allocation', 'Allocation'), ('trade', 'Trade'), ('investment', 'Investment'), ('counterparty', 'Counterparty')], default=None, max_length=50, null=True),
        ),
    ]
