# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0024_auto_20180301_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='entity_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='entity_field_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='venue_allocation_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
