# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0027_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(to='tradepath.Contact')),
            ],
        ),
    ]
