# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0028_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='approval_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradepath.Subscription'),
        ),
    ]
