# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0029_requirement_approval_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='notification_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscription', to='tradepath.Subscription'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='approval_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_subscription', to='tradepath.Subscription'),
        ),
    ]
