# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0030_auto_20180307_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_on', models.DateField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('updated_on', models.DateField(auto_now=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=50, null=True)),
                ('approval_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradepath.Subscription')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradepath.Contact')),
                ('condition', models.ManyToManyField(to='tradepath.Condition')),
                ('path', models.ManyToManyField(to='tradepath.Path')),
            ],
        ),
    ]
