# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-07 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradepath', '0031_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='condition',
        ),
        migrations.AddField(
            model_name='request',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tradepath.Condition'),
        ),
    ]
